# Generated by Django 6.0.7 on 2026-07-22 08:09

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('launched', 'Launched'), ('landed', 'Landed')], default='pending', max_length=20)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('landed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['session', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_altitude_ft', models.FloatField(blank=True, null=True)),
                ('method', models.CharField(blank=True, choices=[('single_station', 'Single station'), ('multi_station', 'Multi station')], max_length=20)),
                ('station_breakdown', models.JSONField(blank=True, help_text='Per-station individual altitude estimates', null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('launch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.launch')),
            ],
        ),
        migrations.AddField(
            model_name='launch',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launches', to='core.session'),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('device_token', models.CharField(default=core.models.generate_device_token, max_length=64, unique=True)),
                ('distance_ft', models.FloatField()),
                ('bearing_degrees', models.FloatField()),
                ('ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.session')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='launch',
            unique_together={('session', 'number')},
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='List of {t, elevation, azimuth} readings')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.launch')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.station')),
            ],
            options={
                'unique_together': {('launch', 'station')},
            },
        ),
    ]
