# Generated by Django 6.0.7 on 2026-07-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='ready',
        ),
        migrations.AddField(
            model_name='station',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
