# Generated by Django 6.0.7 on 2026-07-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_station_ready_station_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
