# Generated by Django 6.0.7 on 2026-07-29 06:37

import core.optical_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_launch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_index', models.PositiveIntegerField()),
                ('local_timestamp_ms', models.BigIntegerField()),
                ('synchronized_timestamp_ms', models.BigIntegerField(blank=True, null=True)),
                ('image_width_px', models.PositiveIntegerField()),
                ('image_height_px', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['station', 'frame_index'],
            },
        ),
        migrations.CreateModel(
            name='TrackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_simulated', models.BooleanField(default=False, help_text='True for mock/synthetic data, never a real flight.')),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='PixelObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixel_x', models.FloatField()),
                ('pixel_y', models.FloatField()),
                ('confidence', models.FloatField(default=1.0)),
                ('observation_source', models.CharField(choices=[('manual', 'Manual'), ('assisted', 'Assisted'), ('automatic', 'Automatic'), ('simulated', 'Simulated')], max_length=20)),
                ('valid', models.BooleanField(default=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=200)),
                ('is_current', models.BooleanField(default=True, help_text='Only one current observation per frame; corrections add a new row instead of overwriting, so raw taps are never lost.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pixel_observations', to='core.frameobservation')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingQualityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct_three_station', models.FloatField(blank=True, null=True)),
                ('pct_two_station', models.FloatField(blank=True, null=True)),
                ('pct_interpolated', models.FloatField(blank=True, null=True)),
                ('mean_residual_m', models.FloatField(blank=True, null=True)),
                ('max_residual_m', models.FloatField(blank=True, null=True)),
                ('num_outliers_rejected', models.PositiveIntegerField(default=0)),
                ('sync_quality_score', models.FloatField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_metrics', to='core.trackingsession')),
            ],
        ),
        migrations.CreateModel(
            name='SynchronizedObservationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synchronized_timestamp_ms', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synchronized_sets', to='core.trackingsession')),
            ],
            options={
                'ordering': ['session', 'synchronized_timestamp_ms'],
            },
        ),
        migrations.AddField(
            model_name='frameobservation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_observations', to='core.trackingsession'),
        ),
        migrations.CreateModel(
            name='FlightEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('first_motion', 'First motion'), ('launch', 'Launch'), ('rail_departure', 'Rail departure'), ('burnout', 'Burnout'), ('apogee', 'Apogee'), ('landing', 'Landing')], max_length=20)),
                ('timestamp_ms', models.BigIntegerField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('detection_method', models.CharField(blank=True, default='', max_length=100)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_events', to='core.trackingsession')),
            ],
            options={
                'ordering': ['session', 'timestamp_ms'],
            },
        ),
        migrations.CreateModel(
            name='TrackingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('station_index', models.PositiveIntegerField(help_text='Display/ordering index - not a hard station-count limit.')),
                ('device_token', models.CharField(default=core.optical_models.generate_optical_device_token, max_length=64, unique=True)),
                ('position_source', models.CharField(choices=[('gps', 'Phone GPS'), ('manual', 'Manual latitude/longitude'), ('surveyed_enu', 'Local surveyed ENU'), ('mock', 'Mock coordinates')], default='mock', max_length=20)),
                ('gps_latitude', models.FloatField(blank=True, null=True)),
                ('gps_longitude', models.FloatField(blank=True, null=True)),
                ('gps_altitude_m', models.FloatField(blank=True, null=True)),
                ('surveyed_x_m', models.FloatField(blank=True, help_text='Local ENU east offset from the launch pad, meters.', null=True)),
                ('surveyed_y_m', models.FloatField(blank=True, help_text='Local ENU north offset from the launch pad, meters.', null=True)),
                ('surveyed_z_m', models.FloatField(blank=True, help_text='Local ENU up offset from the launch pad, meters.', null=True)),
                ('measured_height_m', models.FloatField(blank=True, help_text='Camera height above ground, meters.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.trackingsession')),
            ],
            options={
                'ordering': ['session', 'station_index'],
                'unique_together': {('session', 'station_index')},
            },
        ),
        migrations.CreateModel(
            name='StationCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_width_px', models.PositiveIntegerField()),
                ('image_height_px', models.PositiveIntegerField()),
                ('fov_horizontal_deg', models.FloatField()),
                ('fov_vertical_deg', models.FloatField()),
                ('facing_deg', models.FloatField(help_text='Compass bearing the camera boresight points toward.')),
                ('pitch_deg', models.FloatField(help_text='Boresight elevation angle above the horizon; positive is up.')),
                ('roll_deg', models.FloatField(default=0.0)),
                ('orientation_source', models.CharField(choices=[('sensor', 'Device sensor'), ('manual', 'Manual entry')], default='sensor', max_length=20)),
                ('calibration_target_pixel_x', models.FloatField(blank=True, null=True)),
                ('calibration_target_pixel_y', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='core.trackingstation')),
            ],
        ),
        migrations.AddField(
            model_name='frameobservation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_observations', to='core.trackingstation'),
        ),
        migrations.CreateModel(
            name='TriangulatedPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synchronized_timestamp_ms', models.BigIntegerField()),
                ('x_m', models.FloatField()),
                ('y_m', models.FloatField()),
                ('z_m', models.FloatField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude_m', models.FloatField(blank=True, null=True)),
                ('stations_used', models.JSONField(default=list, help_text='TrackingStation ids used in this solve.')),
                ('stations_used_count', models.PositiveIntegerField(default=0)),
                ('rejected_stations', models.JSONField(default=list)),
                ('residual_error_m', models.FloatField(blank=True, null=True)),
                ('geometry_quality', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triangulated_points', to='core.trackingsession')),
            ],
            options={
                'ordering': ['session', 'synchronized_timestamp_ms'],
            },
        ),
        migrations.CreateModel(
            name='TrajectoryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_ms', models.BigIntegerField()),
                ('raw_x_m', models.FloatField(blank=True, null=True)),
                ('raw_y_m', models.FloatField(blank=True, null=True)),
                ('raw_z_m', models.FloatField(blank=True, null=True)),
                ('filtered_x_m', models.FloatField(blank=True, null=True)),
                ('filtered_y_m', models.FloatField(blank=True, null=True)),
                ('filtered_z_m', models.FloatField(blank=True, null=True)),
                ('is_interpolated', models.BooleanField(default=False)),
                ('is_gap_filled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajectory_points', to='core.trackingsession')),
                ('source_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trajectory_points', to='core.triangulatedpoint')),
            ],
            options={
                'ordering': ['session', 'timestamp_ms'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='frameobservation',
            unique_together={('station', 'frame_index')},
        ),
    ]
