# Generated by Django 6.0.7 on 2026-07-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_frameobservation_trackingsession_pixelobservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationcalibration',
            name='orientation_source',
            field=models.CharField(choices=[('sensor', 'Device sensor'), ('manual', 'Manual entry'), ('geometry_refined', 'Geometry-refined from a tap')], default='sensor', max_length=20),
        ),
    ]
