# Generated by Django 6.0.7 on 2026-07-29 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_stationcalibration_orientation_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frameobservation',
            options={'ordering': ['station', 'flight', 'frame_index']},
        ),
        migrations.CreateModel(
            name='TrackingFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='core.trackingsession')),
            ],
            options={
                'ordering': ['session', 'number'],
                'unique_together': {('session', 'number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='frameobservation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='frameobservation',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='frame_observations', to='core.trackingflight'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='frameobservation',
            unique_together={('station', 'flight', 'frame_index')},
        ),
    ]
