# Generated by Django 6.0.7 on 2026-07-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_frameobservation_options_trackingflight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingstation',
            name='clock_offset_ms',
            field=models.FloatField(blank=True, help_text="Add to this station's local_timestamp_ms to get server time.", null=True),
        ),
        migrations.AddField(
            model_name='trackingstation',
            name='clock_round_trip_ms',
            field=models.FloatField(blank=True, help_text='Round-trip time of the winning sync measurement - lower is better.', null=True),
        ),
        migrations.AddField(
            model_name='trackingstation',
            name='clock_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
