# Generated by Django 6.0.7 on 2026-07-29 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trackingstation_clock_offset_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triangulatedpoint',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='triangulated_points', to='core.trackingflight'),
            preserve_default=False,
        ),
    ]
