# Generated by Django 6.0.7 on 2026-07-29 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_trajectorypoint_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightevent',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flight_events', to='core.trackingflight'),
            preserve_default=False,
        ),
    ]
