# Generated by Django 6.0.7 on 2026-07-30 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_flightevent_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingqualitymetrics',
            name='session',
        ),
        migrations.AddField(
            model_name='trackingqualitymetrics',
            name='flight',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quality_metrics', to='core.trackingflight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackingqualitymetrics',
            name='sync_quality_score',
            field=models.FloatField(blank=True, help_text='Mean clock round-trip time (ms) among contributing stations - lower is better. A raw diagnostic, not a calibrated 0-1 quality score.', null=True),
        ),
    ]
