# Generated by Django 6.0.7 on 2026-08-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_trackingqualitymetrics_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingstation',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Live presence - touched by the WebSocket heartbeat, not a stored connected flag.', null=True),
        ),
    ]
