# Generated by Django 6.0.7 on 2026-08-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_trackingstation_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixelobservation',
            name='facing_deg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pixelobservation',
            name='pitch_deg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pixelobservation',
            name='observation_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('assisted', 'Assisted'), ('automatic', 'Automatic'), ('orientation', 'Orientation'), ('simulated', 'Simulated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pixelobservation',
            name='pixel_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pixelobservation',
            name='pixel_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
