# Generated by Django 6.0.7 on 2026-08-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pixelobservation_facing_deg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingsession',
            name='live_flight_started_at',
            field=models.DateTimeField(blank=True, help_text='Set when countdown_start is relayed, cleared on flight_landed - lets a reconnecting station (core.optical_consumers) learn whether it should currently be recording, the same way TrackingStation.last_seen_at backs live presence.', null=True),
        ),
    ]
